export const SET_ACTIVE_OPTION = 'SET_ACTIVE_OPTION';
export const SET_FEATURES = 'SET_FEATURES';
export const SET_LEGEND_ACTIVE_OPTION = 'SET_LEGEND_ACTIVE_OPTION';
export const SET_INFO_ACTIVE = 'SET_INFO_ACTIVE';