export const SET_ACTIVE_OPTION = 'SET_ACTIVE_OPTION';
export const SET_CURRENT_FEATURE = 'SET_CURRENT_FEATURE';
export const SET_LEGEND_ACTIVE_OPTION = 'SET_LEGEND_ACTIVE_OPTION';
export const SET_INFO_ACTIVE = 'SET_INFO_ACTIVE';
export const SET_ANALYSIS_ACTIVE_OPTION = 'SET_ANALYSIS_ACTIVE_OPTION';
export const CHANGE_MORE_ANALYSIS = 'CHANGE_MORE_ANALYSIS';

export const SET_MORE_STATS_OPTION = 'SET_MORE_STATS_OPTION';
export const SET_FEATURES = 'SET_FEATURES';
export const ADD_LAYER = 'ADD_LAYER';
export const REMOVE_LAYER = 'REMOVE_LAYER';
export const SET_CLUSTER_ACTIVE = 'SET_CLUSTER_ACTIVE';


